version: '3.8'

services:
  user-service:
    build: .
    ports:
      - '3000:3000'
      - '5555:5555' #port for prisma stduio
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    environment:
      DATABASE_URL: postgres://recipe:RecipePassword@postgres:5432/recipe_db # Example, adjust according to your setup
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: RecipePassword
      POSTGRES_DB: recipe_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
